FROM r-base 

LABEL version="0.1"
LABEL description="This image encapsulates an environment to run the rethinking package for \
    the statistics course statistical rethinking on a simple linux image"

RUN apt-get update && apt install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev 

ARG DOWNLOAD_STATIC_LIBV8=1

RUN R -e 'dotR <- file.path(Sys.getenv("HOME"), ".R") \
    if (!file.exists(dotR)) dir.create(dotR) \
    M <- file.path(dotR, "Makevars") \
    if (!file.exists(M)) file.create(M) \
    cat("\nCXX14FLAGS=-O3 -march=native -mtune=native -fPIC",\
        "CXX14=g++-10", \
        file = M, sep = "\n", append = TRUE)'

RUN R -e "install.packages('rstan', repos = 'https://cloud.r-project.org/', dependencies=TRUE)"

RUN R -e "install.packages(devtools)"
RUN R -e 'install.packages(c("coda","mvtnorm","devtools","loo","dagitty"))'
RUN R -e 'devtools::install_github("rmcelreath/rethinking")'

